### ISSUE TITLE
Model Save Error

### ISSUE THREAD

**Issue by SaifurRahmanMohsin** [Shahiem/TodoList#4]
I use SQLite on one of my October installs and I realize that this plugin uses direct SQL query [here](https://github.com/Shahiem/TodoList/blob/22b68579ddb76fb14962cdf8d67a859aa3e92d66/controllers/Projects.php#L48) which throws an error like this...
![Screenshot of Error](http://i.imgur.com/rH7vR7P.png)

SQLite doesn't come with the information_schema table, hence this error. Perhaps the logic could be improved? I've been exploring the code a bit trying to understand it and I haven't been quite able to figure out the logic in that section. Could you take a look to see if this issue can be fixed, preferably using Laravel's Eloquent approach instead of the direct DB query, so that it's more database-neutral. Thanks for the plugin by the way!

**Comment by Shahiem** [comment]
Bug fixed in the next version.

**Comment by SaifurRahmanMohsin** [comment]
Great... Thanks!
